### ISSUE TITLE
Device selection drop down empty on 1.0.1

### ISSUE THREAD

**Issue by NuclearMeltdown** [ThioJoe/Dynamic-Lighting-Key-Indicator#6]
Works fine on 1.0.0, 1.0.1 doesn't list any devices.

1.0.0:
![image](https://github.com/user-attachments/assets/ab3a59dc-1edd-40a9-b460-ce417e1bb4a0)

1.0.1:
![image](https://github.com/user-attachments/assets/8debfe72-d309-4298-82d9-67defcdf8ffb)

**Comment by ThioJoe** [comment]
Ok try the new 1.0.1.1, it's on the same release.
